# Generated by Django 5.2.3 on 2025-11-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="anonymous_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
