# Generated by Django 5.2.3 on 2025-11-17 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_conversation_anonymous_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
